# Monitor Scaling for 4K Display (1.5 is more stable for fractional scaling)
monitor = , preferred, auto, 1.5

# Performance and Stability Optimizations
misc {
    vfr = false # Force constant frame rate to prevent Nvidia wake-up flickering
    vrr = 0
    disable_hyprland_logo = true
    background_color = 0x000000
}

decoration {
    blur {
        enabled = false
    }
    shadow {
        enabled = false
    }
}

# Increase font size for better readability on high DPI

# Disable TrackPoint (red dot)
device {
    name = tpps/2-elan-trackpoint
    enabled = false
}

# Auto launch Valent, Polkit Agent, 
exec-once = valent --gapplication-service
exec-once = /usr/lib/polkit-kde-authentication-agent-1

# Toggle Touchscreen
bind = Super+Shift, T, exec, ~/.local/bin/toggle_touchscreen.sh

# Polkit Agent
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

# ########################################################
# FIXES FOR FLICKERING (Nvidia + Wayland)
# ########################################################

# Disable Immediate Mode (Tearing) for Terraria specifically
# to avoid screen tearing which can look like flickering
windowrule = immediate 0, match:class ^(steam_app_105600)$

cursor {
    no_hardware_cursors = true
}
