local v = require("hyprland/vars")

-- Apps (GTK, Electron, browsers) often request maximize/fullscreen on map.
-- That looks like "opened fullscreen" on a tiling layout. Super+F still works.
hl.window_rule({
  name = "suppress-maximize-fullscreen-events",
  match = { class = ".*" },
  suppress_event = "maximize fullscreen",
})

-- Opacity when not fullscreen
hl.window_rule({
  name = "opacity-non-fullscreen",
  match = { fullscreen = false },
  opacity = string.format("%s override", v.window_opacity),
})

hl.window_rule({
  name = "opaque-native",
  match = { class = "foot|equibop|imv|swappy" },
  opaque = true,
})

hl.window_rule({
  name = "center-floating-wayland",
  match = { float = true, xwayland = false },
  center = true,
})

local float_classes = {
  "guifetch", "yad", "zenity", "wev",
  "org\\.gnome\\.FileRoller", "file-roller",
  "blueman-manager", "com\\.github\\.GradienceTeam\\.Gradience",
  "feh", "imv", "system-config-printer",
}
for _, cls in ipairs(float_classes) do
  hl.window_rule({ match = { class = cls }, float = true })
end

local function float_size_center(name, class, title, size)
  local match = { class = class }
  if title then match.title = title end
  hl.window_rule({ name = name .. "-float", match = match, float = true })
  hl.window_rule({ name = name .. "-size", match = match, size = size })
  hl.window_rule({ name = name .. "-center", match = match, center = true })
end

float_size_center("nmtui", "foot", "nmtui", { "60%", "70%" })
float_size_center("gnome-settings", "org\\.gnome\\.Settings", nil, { "70%", "80%" })
float_size_center("pavu", "org\\.pulseaudio\\.pavucontrol|yad-icon-browser", nil, { "60%", "70%" })
float_size_center("nwg-look", "nwg-look", nil, { "50%", "60%" })

-- Waydroid
hl.window_rule({
  name = "waydroid",
  match = { class = "waydroid" },
  workspace = "4",
  float = true,
  center = true,
})
-- Size rule generated by waydroid-hypr-size-sync.sh
pcall(require, "hyprland/waydroid-size")

-- Special workspaces
hl.window_rule({ match = { class = "btop" }, workspace = "special:sysmon" })
hl.window_rule({
  match = { class = "feishin|Spotify|Supersonic|Cider|com\\.msob7y\\.namida|namida" },
  workspace = "special:music",
})
hl.window_rule({
  match = { initial_title = "Spotify( Free)?" },
  workspace = "special:music",
})
hl.window_rule({
  match = { class = "discord|equibop|vesktop|whatsapp" },
  workspace = "special:communication",
})
hl.window_rule({ match = { class = "Todoist" }, workspace = "special:todo" })

-- Dialogs
local dialog_titles = {
  "(Select|Open)( a)? (File|Folder)(s)?",
  "File (Operation|Upload)( Progress)?",
  ".* Properties",
  "Export Image as PNG",
  "GIMP Crash Debug",
  "Save As",
  "Library",
}
for _, title in ipairs(dialog_titles) do
  hl.window_rule({ match = { title = title }, float = true })
end

-- Picture-in-Picture
hl.window_rule({
  name = "pip",
  match = { title = "Picture(-| )in(-| )[Pp]icture" },
  move = { "100%-w-2%", "100%-w-3%" },
  keep_aspect_ratio = true,
  float = true,
  pin = true,
})

-- Steam
hl.window_rule({ match = { class = "steam" }, rounding = 10 })
hl.window_rule({
  match = { class = "steam", title = "Friends List" },
  float = true,
})
hl.window_rule({
  match = { class = "steam_app_[0-9]+" },
  immediate = true,
})

-- Terraria: disable tearing (from hypr-user.conf)
hl.window_rule({
  match = { class = "^steam_app_105600$" },
  immediate = false,
})

hl.window_rule({
  match = { class = "com-atlauncher-App", title = "ATLauncher Console" },
  float = true,
})

hl.window_rule({
  match = { class = "fusion360\\.exe", title = "Fusion360|(Marking Menu)" },
  no_blur = true,
})

-- XWayland popups
hl.window_rule({
  name = "xwayland-popups",
  match = { xwayland = true, title = "win[0-9]+" },
  no_dim = true,
  no_shadow = true,
  rounding = 10,
})

-- Workspace rules (smart gaps for single window)
hl.workspace_rule({
  workspace = "w[tv1]s[false]",
  gaps_out = v.single_window_gaps_out,
})
hl.workspace_rule({
  workspace = "f[1]s[false]",
  gaps_out = v.single_window_gaps_out,
})

-- Layer rules
hl.layer_rule({
  match = { namespace = "launcher" },
  blur = true,
})
hl.layer_rule({
  match = { namespace = "vicinae" },
  animation = "popin 70%",
})
